name: Run UI Automation Tests

on: 
  workflow_dispatch:
    inputs:
      Module:
        required: true
        type: choice
        description: Module 
        default: "all-module"
        options:
          - all-module
          - patient
          - home
      Submodule:
        required: true
        type: string
        default: "all-submodule"


jobs:
  apptest:
    uses: fauzifnMR/learn-github/.github/workflows/submodule.yml@main
    with:
      path:  ./module/${{github.event.inputs.Module}}/${{github.event.inputs.Submodule}}/${{github.event.inputs.Submodule}}.txt
      Module: {{github.event.inputs.Module}}
      SubModule: {{github.event.inputs.Submodule}}


    