name: Run UI Automation Tests

on: 
  workflow_dispatch:
    inputs:
      Module:
        required: true
        type: choice
        description: Module 
        default: "all-module"
        options:
          - all-module
          - patient
          - home
      Submodule:
        required: true
        type: string
        default: "all-submodule"
      Parallel-Number:
        default: 4
        required: true

jobs:
  starter:
    runs-on: ubuntu-latest
    outputs:
      matrix-submodule: ${{ steps.set-matrix-submodule.outputs.matrix-submodule }}
      matrix-module: ${{ steps.set-matrix-module.outputs.matrix-module }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Read Submodule
        # if: ${{github.event.inputs.Module != 'all-module' && github.event.inputs.Submodule != 'all-submodule'}}
        id: package-submodule
        uses: juliangruber/read-file-action@v1
        with:
          path: ./module/${{github.event.inputs.Module}}/${{github.event.inputs.Submodule}}/${{github.event.inputs.Submodule}}.txt

      # - name: Read Module
      #   # if: ${{github.event.inputs.Module != 'all-module' && github.event.inputs.Submodule == 'all-submodule'}}
      #   id: package-module
      #   uses: juliangruber/read-file-action@v1
      #   with:
      #     path: ./module/${{github.event.inputs.Module}}/${{github.event.inputs.Submodule}}/${{github.event.inputs.Submodule}}.txt
      - name: Get Matrix Feature Submodule 
        # if: ${{github.event.inputs.Module != 'all-module' && github.event.inputs.Submodule != 'all-submodule'}}
        id: set-matrix-submodule
        run: |
          #!/bin/bash
          pwd
          ls
          JOB_STRATEGY_MATRIX_SUBMODULE=$(node -e "let r=[];var f='${{ steps.package-submodule.outputs.content }}'.split(',');var chunkSize = Math.ceil(f.length/${{github.event.inputs.Parallel-Number}}); for(let i = 0; i < f.length; i += chunkSize) { const chunk = f.slice(i, i + chunkSize); r.push(chunk.join(','))}; console.log(JSON.stringify(r))";)
          echo $JOB_STRATEGY_MATRIX_SUBMODULE
          echo "::set-output name=matrix-submodule::$JOB_STRATEGY_MATRIX_SUBMODULE"
      # - name: Get Matrix Feature Module
      #   if: ${{github.event.inputs.Module != 'all-module' && github.event.inputs.Submodule == 'all-submodule'}} 
      #   id: set-matrix-module
      #   run: |
      #     #!/bin/bash
      #     pwd
      #     ls
      #     JOB_STRATEGY_MATRIX_MODULE=$(node -e "let r=[];var f='${{ steps.package-module.outputs.content }}'.split(',');var chunkSize = Math.ceil(f.length/${{github.event.inputs.Parallel-Number}}); for(let i = 0; i < f.length; i += chunkSize) { const chunk = f.slice(i, i + chunkSize); r.push(chunk.join(','))}; console.log(JSON.stringify(r))";)
      #     echo $JOB_STRATEGY_MATRIX_MODULE
      #     echo "::set-output name=matrix-module::$JOB_STRATEGY_MATRIX_MODULE"

 



  run-testing:
    needs: starter
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        feature-module: ${{fromJson(needs.starter.outputs.matrix-module)}}
        feature-submodule: ${{fromJson(needs.starter.outputs.matrix-submodule)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: run test
        run: |
          if [ ${{github.event.inputs.Module == 'all-module' && github.event.inputs.Submodule == 'all-submodule' && github.event.inputs.Features == 'critical'}} ]; then
            chmod +x gradlew
            echo "${{matrix.feature-module}}"
          elif [ ${{github.event.inputs.Module != 'all-module' && github.event.inputs.Submodule == 'all-submodule'}} ]; then
            chmod +x gradlew
            echo "${{matrix.feature-submodule}}"
          elif [ ${{github.event.inputs.Module != 'all-module'  && github.event.inputs.Submodule != 'all-submodule'}} ]; then
            chmod +x gradlew
            echo "${{matrix.feature-module}}"
          else
            chmod +x gradlew
            echo ${{matrix.feature-submodule}}
          fi