name: Run UI Automation Tests

on: 
  workflow_dispatch:
    inputs:
      Module:
        required: true
        type: choice
        description: Module 
        default: "all-module"
        options:
          - all-module
          - patient
          - home
      Submodule:
        required: true
        type: string
        default: "all-submodule"
      Parallel-Number:
        default: 4
        required: true

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      foldersubmodule: ${{steps.set-variables.outputs.foldersubmodule}}
    name: Set Variables
    steps:
    - id: set-variables
      run: |
        echo "::set-output name=foldersubmodule::"


  get-feature-submodule:
    runs-on: ubuntu-latest
    outputs:
      matrixs: ${{ steps.set-matrix-submodule.outputs.matrix }}
      foldersubmodule: ${{steps.set-variables.outputs.foldersubmodule}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get Matrix Feature Submodule 
        id: set-matrix-submodule
        run: |
          #!/bin/bash
          pwd
          ls
          sudo su
          JOB_STRATEGY_MATRIX_SUBMODULE=$(node -e "const fs = require('fs'); let r=[]; let data = fs.readFileSync(`'./module/${{github.event.inputs.Module}}/${{github.event.inputs.Submodule}}/${{github.event.inputs.Submodule}}.txt'`, 'utf-8'); console.log(data); var f= `${data}`.toString().split(',');var chunkSize = Math.ceil(f.length/${{github.event.inputs.Parallel-Number}});for(let i = 0; i < f.length; i += chunkSize) {  const chunk = f.slice(i, i + chunkSize); r.push(chunk.join(','))}")
          echo $JOB_STRATEGY_MATRIX_SUBMODULE
          echo "::set-output name=job-strategy-matrix-module::$JOB_STRATEGY_MATRIX_SUBMODULE"