name: Run UI Automation Tests

on: 
  workflow_dispatch:
    inputs:
      Module:
        required: true
        type: choice
        description: Module 
        default: "all-module"
        options:
          - all-module
          - patient
          - home
      Submodule:
        required: true
        type: string
        default: "all-submodule"
      Parallel-Number:
        default: 4
        required: true

jobs:  
  get-feature-submodule:
    if: ${{github.event.inputs.Module != 'all-module'}} && ${{github.event.inputs.Submodule != 'all-submodule'}}
    runs-on: ubuntu-latest
    outputs:
      matrixs: ${{ steps.set-matrix-submodule.outputs.matrix }}
    steps:
    - name: Checkout
        uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Get Matrix Feature Submodule 
      id: set-matrix-submodule
      run: |
        cd module
        JOB_STRATEGY_MATRIX_SUBMODULE=$(node -e "const fs = require('fs');let r=[];let name = './${{github.event.inputs.Module}}/${{github.event.inputs.Submodule}}/${{github.event.inputs.Submodule}}.txt';let data = fs.readFileSync(name, 'utf-8');var f=`${data.toString()}`.split(',');var chunkSize = Math.ceil(f.length/${{github.event.inputs.Parallel-Number}});for(let i = 0; i < f.length; i += chunkSize) {  const chunk = f.slice(i, i + chunkSize); r.push(chunk.join(','))}; console.log(JSON.stringify(r))";)
        echo $JOB_STRATEGY_MATRIX_SUBMODULE
        echo "::set-output name=job-strategy-matrix-module::$JOB_STRATEGY_MATRIX_SUBMODULE"