# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
    inputs:
      Module:
        required: true
        default: "all"
        type: choice
        options:
          - home
          - patinent
          - all
      Submodule:
        required: true
        default: "all"
        type: string
      Features:
        required: true
        default: "critical"
        type: string

  workflow_call:
    inputs:
      Module:
        required: true
        type: string
        default: "all"
      Submodule:
        required: true
        type: string
        default: "all"
      Features:
        required: true
        default: "critical"
        type: string

jobs:
  build:
    runs-on:
      ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Feature File Critical Scenarios
        if: ${{inputs.Module == 'all'  &&  inputs.Submodule == 'all' &&  inputs.Features == 'critical' }};
        id: filescenarios
        uses: juliangruber/read-file-action@v1
        with:
            path: './module/critical.txt'

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Yarn
        run: |
          npm install -g yarn
          sudo yarn install
          sudo yarn add custom-env
      
      - id: getfeatures
        run: |
          pwd
          ls -a
          if ${{inputs.Module == 'all'  &&  inputs.Submodule == 'all' &&  inputs.Features == 'critical' }}; then
            touch filefeature.txt
            echo "${{steps.filescenarios.outputs.content}}" > filefeature.txt
          elif ${{inputs.Module != 'all'  &&  inputs.Submodule != 'all' && (inputs.Features == 'all' || inputs.Features == 'critical')}}; then
            PATH_FEATURES=mrtest/${{inputs.Module}}/${{inputs.Submodule}} node apptest.js
          elif ${{inputs.Module != 'all'  &&  inputs.Submodule == 'all' && (inputs.Features == 'all' || inputs.Features == 'critical')}}; then
            PATH_FEATURES=mrtest/${{inputs.Module}} node apptest.js
          elif ${{inputs.Module == 'all'  &&  inputs.Submodule == 'all' &&  inputs.Features == 'all'}}; then
            PATH_FEATURES=mrtest node apptest.js
          else
            touch filefeature.txt
            echo "${{inputs.Features}}" > filefeature.txt
          fi
      - name: read file
        run: |
          sudo su
          pwd
          ls -a
          cat filefeature.txt
